<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="Task3_GLV_HMI" Id="{e0cf7c83-d064-4656-bc92-63a5474cd7bc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Task3_GLV_HMI
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	iPageNumber	:LREAL;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Task3_GLV_HMI">
      <LineId Id="20" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>